spring:
  application:
    name: user

  datasource:
    url:  jdbc:postgresql://localhost:5433/postgres
    username: postgres-user
    password: postgres-password
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080


