spring:
  application:
    name: user

  datasource:
    url:  jdbc:postgresql://localhost:5433/ms_email_ms
    username: postgres-user
    password: postgres-password
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: org.hibernate.dialect.PostgreSQLDialect
      dialect: org.hibernate.dialect.PostgreSQLDialect



  rabbitmq:
    addresses: "amqps://gllsxgbh:OThnUUQo3FsvtqDg20pAmdhTnOLqlkgy@kebnekaise.lmq.cloudamqp.com/gllsxgbh"
    username: "gllsxgbh"
    password: "OThnUUQo3FsvtqDg20pAmdhTnOLqlkgy"
    virtual-host: "gllsxgbh"

server:
  port: 8080


