spring:
  application:
    name: user
  datasource:
    url: ${USER_DS_URL}
    username: ${USER_DS_USERNAME}
    password: ${USER_DS_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    addresses: ${USER_RABBITMQ_ADDRESSES}
    username: ${USER_RABBITMQ_USERNAME}
    password: ${USER_RABBITMQ_PASSWORD}
    virtual-host: ${USER_RABBITMQ_VHOST}
    port: ${USER_RABBITMQ_PORT}

  flyway:
    enabled: true
    locations: ${FLYWAY_LOCATIONS}
    baseline-on-migrate: true

server:
  port: ${USER_SERVICE_PORT}
