spring:
  application:
    name: user
  datasource:
    url: ${USER_DS_URL:jdbc:postgresql://localhost:5430/ms_user_ms}
    username: ${USER_DS_USERNAME:postgres-user}
    password: ${USER_DS_PASSWORD:postgres-password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    addresses: ${USER_RABBITMQ_ADDRESSES:amqps://gllsxgbh:OThnUUQo3FsvtqDg20pAmdhTnOLqlkgy@kebnekaise.lmq.cloudamqp.com/gllsxgbh}
    username: ${USER_RABBITMQ_USERNAME:gllsxgbh}
    password: ${USER_RABBITMQ_PASSWORD:OThnUUQo3FsvtqDg20pAmdhTnOLqlkgy}
    virtual-host: ${USER_RABBITMQ_VHOST:gllsxgbh}
    port: ${USER_RABBITMQ_PORT:5672}

  flyway:
    enabled: true
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}
    baseline-on-migrate: true

server:
  port: ${USER_SERVICE_PORT:8081}
